# The instanceName should be the fully qualified name of the DataOS Instance like "demo-test-01.dataos.io"
instanceName: 
# The Prime APIKEY
primeApiKey: 
# The Prime Account ID
primeAccountId: 

# The mode can be api | prime
mode: prime

name: dataos-manager
namespace: dataos-manager
application: prime-dataos-io
label: dataos-manager
serviceAccountName: dataos-manager-sa

image:
  name: docker.io/tmdcio/dataos-manager
  tag: 0.19.9

replicas: 1

priorityClassName: system-cluster-critical

# Include an image pull secret
# imagePullSecrets: 
#   name: dataos-manager-pull-secret

# Include install files as a Volume from a ConfigMap or Secret
# volumes:
#   - name: install-files
#     configMap:
#       name: dataos-install-files
# volumeMounts:
#   - name: install-files
#     mountPath: "/etc/dataos/install"

# Include the cloud kernel json
# cloudKernelJson: 

containerPorts:
  - name: http
    containerPort: 20220
  - name: metrics
    containerPort: 20222

services:
  - name: dataos-manager
    ports:
      - name: http
        port: 20220
      - name: metrics
        port: 20222

resources:
  requests:
    cpu: 150m
    memory: 400Mi
rbac:
  serviceAccount: true
  clusterRoleBinding:
    roleRef:
      kind: ClusterRole
      apiGroup: rbac.authorization.k8s.io
      name: cluster-admin

logLevel: info
metaProductName: dataos
metaMyName: dataos-manager

httpPort: 20220
httpScheme: http
tlsCrtFile: /etc/dataos/certs/tls.crt
tlsKeyFile: /etc/dataos/certs/tls.key
baseUriPath: /manager
metricPort: 20222
ginMode: release

homeDir: /opt/dataos/home
operateSubDir: operate
helmFetchSubDir: charts
templateSubDir: deploy
renderSubDir: rendered
defaultChartRepo: dataos-base

helmBinary: /usr/local/bin/helm
sopsBinary: /usr/local/bin/sops
dataosCtlBinary: /usr/local/bin/dataos-ctl
dataosCtlScriptDir: /opt/dataos
dataosCtlBaseConfigDir: /etc/dataos

pulsarAdminServiceUrl: http://pulsar-broker.caretaker.svc.cluster.local:8080

mdcUrl: 
hephUrl: https://prime.tmdata.io/heph/api/v1
enablePrimeSyncUp: true
enablePrimeSyncExecute: true
primeSyncIntervalUp: 10m
primeSyncIntervalExecute: 5m
instanceSyncTarget: plutus
plutusUrl: https://prime.tmdata.io/plutus/api/v1

gitOpsProviderType: 
gitOpsRootDir: 
gitSubDir: git
gitTMinus1Dir: git-t-1
gitSubSubDir: git
gitZipFileName: gitops.zip
gitopsInstallManifestFileName: dataos.release.yaml
gitopsTempDir: /opt/dataos/home/tmp

executeTasksProviderType: 
executeTasksRootDir: 

s3Endpoint: 
s3Region: 
s3Bucket: 
s3AccessKey: 
s3SecretKey: 
s3DisableSsl: false
s3ForcePathStyle: false
azureBlobStorageAccount: 
azureBlobEndpointSuffix: 
azureBlobContainer: 
azureBlobSecretKey: 

# Defines the resource quota for the dataos-manager namespace
resourceQuota:
  podsQuota: 5
  priorityClasses:
  - system-cluster-critical

# Use to Enable a Service Monitor
# serviceMonitor:
#   endpoints:
#   - targetPort: metrics
#     interval: 30s
#     scrapeTimeout: 30s
