{{ if .Values.imagePullSecret -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.imagePullSecret.name }}
  {{- if .Values.imagePullSecret.annotations }}
  annotations:
{{ toYaml .Values.imagePullSecret.annotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ .Values.label }}
    app.kubernetes.io/name: '{{ .Values.label }}'
    app.kubernetes.io/component: 'secret'
    app.kubernetes.io/part-of: '{{ .Values.application }}'
    {{- if .Values.imagePullSecret.labels }}
{{ toYaml .Values.imagePullSecret.labels | indent 4 }}
    {{- end }}
type: {{ .Values.imagePullSecret.type }}
data:
{{ toYaml .Values.imagePullSecret.data | indent 2 }}
{{- end }}