{{ if .Values.initContainers -}}
{{- $system := .Values.application -}}
{{- range $initContainer := .Values.initContainers }}
{{ if $initContainer.secretEnvironment -}}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $initContainer.namespace }}
  name: {{ $initContainer.name }}-env
  labels:
    app: {{ $initContainer.label }}
    app.kubernetes.io/name: '{{ $initContainer.name | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/component: 'secret'
    app.kubernetes.io/part-of: '{{ $system }}'
type: Opaque
data:
  {{- range $conf, $value := $initContainer.secretEnvironment }}
  {{ if $value -}}
  {{$conf}}: {{ $value | b64enc | quote }}
  {{- else }}
  {{$conf}}: ""
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}