{{ if .Values.cloudKernelJson -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: cloud-kernel-json
  labels:
    app: {{ .Values.label }}
    app.kubernetes.io/name: '{{ .Values.label }}'
    app.kubernetes.io/component: 'secret'
    app.kubernetes.io/part-of: '{{ .Values.application }}'
type: Opaque
data:
  .dataos.ck.config.json: |
    {{ .Values.cloudKernelJson }}
{{- end }}