apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}-env
  labels:
    app: {{ .Values.label }}
    app.kubernetes.io/name: '{{ .Values.label }}'
    app.kubernetes.io/component: 'secret'
    app.kubernetes.io/part-of: '{{ .Values.application }}'
type: Opaque
data:
  PRIME_APIKEY: {{ .Values.primeApiKey | b64enc | quote }}
  PRIME_ACCOUNT_ID: {{ .Values.primeAccountId | b64enc | quote }}
  {{- if .Values.hephApiKey }}
  HEPH_APIKEY: {{ .Values.hephApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.ageRecipient }}
  AGE_RECIPIENT: {{ .Values.ageRecipient | b64enc | quote }}
  {{- end }}
  {{- if .Values.ageKey }}
  AGE_KEY: {{ .Values.ageKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secretEnvironment }}
  {{- range $conf, $value := .Values.secretEnvironment }}
  {{ $conf }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
