apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}-env
  labels:
    app: {{ .Values.label }}
    app.kubernetes.io/name: '{{ .Values.label }}'
    app.kubernetes.io/component: 'secret'
    app.kubernetes.io/part-of: '{{ .Values.application }}'
type: Opaque
data:
  LICENSE_KEY: {{ .Values.licenseKey | b64enc | quote  }}
  PRIME_APIKEY: {{ .Values.primeApiKey | b64enc | quote }}
  PRIME_CLOUD_USERNAME: {{ .Values.primeCloudUserName | b64enc | quote }}
  PRIME_CLOUD_PASSWORD: {{ .Values.primeCloudPassword | b64enc | quote }} 
{{- if eq .Values.gitopsProviderType "s3" }}
  GITOPS_S3_ACCESSKEY: {{ .Values.gitopsS3AccessKey | b64enc | quote }}
  GITOPS_S3_SECRETKEY: {{ .Values.gitopsS3SecretKey | b64enc | quote }}
{{- end }}
{{- if eq .Values.gitopsProviderType "azurefile" }}
  GITOPS_AZURE_FILE_ACCESS_KEY: {{ .Values.gitopsAzureFileAccessKey | b64enc | quote  }}
{{- end }}
{{- if .Values.decryptUsername }}
  DECRYPT_USERNAME: {{ .Values.decryptUsername | b64enc | quote }}
{{- else }}
  DECRYPT_USERNAME: {{ .Values.primeCloudUserName | b64enc | quote }}
{{- end }}
{{- if .Values.decryptPassword }}
  DECRYPT_PASSWORD: {{ .Values.decryptPassword | b64enc | quote }}
{{- else }}
  DECRYPT_PASSWORD: {{ .Values.primeCloudPassword | b64enc | quote }}
{{- end }}
{{- if .Values.helmPrimeCloudUserName }}
  HELM_PRIME_CLOUD_USERNAME: {{ .Values.helmPrimeCloudUserName | b64enc | quote }}
{{- else }}
  HELM_PRIME_CLOUD_USERNAME: {{ .Values.primeCloudUserName | b64enc | quote }}
{{- end }}
{{- if .Values.helmPrimeCloudPassword }}
  HELM_PRIME_CLOUD_PASSWORD: {{ .Values.helmPrimeCloudPassword | b64enc | quote }}
{{- else }}
  HELM_PRIME_CLOUD_PASSWORD: {{ .Values.primeCloudPassword | b64enc | quote }}
{{- end }}
  IMAGE_REPOSITORY_TYPE: {{ .Values.imageRepositoryType | b64enc | quote }}
  IMAGE_REPOSITORY_SECRET_NAME: {{ .Values.imageRepositorySecretName | b64enc | quote }}
{{- if .Values.imageRepositoryAccessConfigUsername }}
  IMAGE_REPOSITORY_ACCESS_CONFIG_USERNAME: {{ .Values.imageRepositoryAccessConfigUsername | b64enc | quote }}
{{- else }}
  IMAGE_REPOSITORY_ACCESS_CONFIG_USERNAME: {{ .Values.primeCloudUserName | b64enc | quote }}
{{- end }}
{{- if .Values.imageRepositoryAccessConfigPassword }}
  IMAGE_REPOSITORY_ACCESS_CONFIG_PASSWORD: {{ .Values.imageRepositoryAccessConfigPassword | b64enc | quote }}
{{- else }}
  IMAGE_REPOSITORY_ACCESS_CONFIG_PASSWORD: {{ .Values.primeCloudPassword | b64enc | quote }}
{{- end }}