apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}-env
  labels:
    app: {{ .Values.label }}
    app.kubernetes.io/name: '{{ .Values.label }}'
    app.kubernetes.io/component: 'secret'
    app.kubernetes.io/part-of: '{{ .Values.application }}'
type: Opaque
data:
  PRIME_APIKEY: {{ .Values.primeApiKey | b64enc | quote }}
  PRIME_CLOUD_USERNAME: {{ .Values.primeCloudUserName | b64enc | quote }}
  PRIME_CLOUD_PASSWORD: {{ .Values.primeCloudPassword | b64enc | quote }}
{{- if eq .Values.gitopsProviderType "s3" }}
  GITOPS_S3_ACCESSKEY: {{ .Values.gitopsS3AccessKey | b64enc | quote }}
  GITOPS_S3_SECRETKEY: {{ .Values.gitopsS3SecretKey | b64enc | quote }}
{{- end }}
{{- if eq .Values.gitopsProviderType "azurefile" }}
  GITOPS_AZURE_FILE_ACCESS_KEY: {{ .Values.gitopsAzureFileAccessKey | b64enc | quote  }}
{{- end }}
