{{- if .Values.rbac }}
{{- if .Values.rbac.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-sa
  namespace: {{ .Values.namespace }}
  {{- if .Values.rbac.annotations }}
  annotations:
{{ toYaml .Values.rbac.annotations | indent 4 }}
  {{- end }}
  labels:
    app: {{ .Values.label }}
    app.kubernetes.io/name: {{ .Values.label }}
    app.kubernetes.io/component: 'service-account'
    app.kubernetes.io/part-of: '{{ .Values.application }}'
    {{- if .Values.rbac.labels }}
{{ toYaml .Values.rbac.labels | indent 4 }}
    {{- end }}
{{- end }}
{{- end }}