{{ if .Values.sideCars -}}
{{- $system := .Values.application -}}
{{- range $sideCar := .Values.sideCars }}
{{ if $sideCar.secretEnvironment -}}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ $sideCar.namespace }}
  name: {{ $sideCar.name }}-env
  labels:
    app: {{ $sideCar.label }}
    app.kubernetes.io/name: '{{ $sideCar.name | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/component: 'secret'
    app.kubernetes.io/part-of: '{{ $system }}'
type: Opaque
data:
  {{- range $conf, $value := $sideCar.secretEnvironment }}
  {{$conf}}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}